name       : perl-term-readkey
version    : 2.37
release    : 2
source     :
    - http://search.cpan.org/CPAN/authors/id/J/JS/JSTOWE/TermReadKey-2.37.tar.gz : 4a9383cf2e0e0194668fe2bd546e894ffad41d556b41d2f2f577c8db682db241
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : A perl module for simple terminal control
description: |
    Term::ReadKey is a compiled perl module dedicated to providing simple
    control over terminal driver modes (cbreak, raw, cooked, etc.)
    support for non-blocking reads, if the architecture allows, and some
    generalized handy functions for working with terminals.  One of the
    main goals is to have the functions as portable as possible, so you
    can just plug in "use Term::ReadKey" on any architecture and have a
    good likelyhood of it working.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
